apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: healthcheck-role-cr
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods", "services", "deployments", "nodes"]
  verbs: ["get", "list"]
- apiGroups: ["velero.io"]
  resources: ["backups"]
  verbs: ["list"]