{{- if eq .Values.type "deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}
  {{- .Release.Name.labels | nindent 4 }}
spec:
  replicas: {{ .Values.sampleDeployment.replicas }}
  selector:
    matchLabels:
      app: k8shealthcheck
    {{- .Release.Name.labels | nindent 4 }}
  template:
    metadata:
      labels:
        app: k8shealthcheck
      {{- .Release.Name.labels | nindent 4 }}
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-cm
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
      restartPolicy: OnFailure
{{- end }}