apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa
  labels:
   {{- .Release.Name.labels | nindent 4 }}
  annotations:
    {{- toYaml .Values.sa.serviceAccount.annotations | nindent 4 }}